### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by fayasnoushad**

### CODE REVIEW

**Review by zeeshanmahar007 — CHANGES_REQUESTED** [review]
I think this need more changes. icon is still not clear.

**Comment by fayasnoushad** [comment]
Not changed icons. Use [shields.io](https://sheilds.io) badges for icons like my profile.

**Comment by fayasnoushad** [comment]
I just changed 2 lines stats in same line

**Review by fayasnoushad — COMMENTED** [review]
Width changed to current width.

**Review by zeeshanmahar007 — APPROVED** [review]
Thank you for contribution.

**Pull request merged**
